import { Inter } from "next/font/google";
import "./globals.css";
import React, { ReactNode } from "react";
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <ClerkProvider>
            <html lang='es'>
            <body className="min-h-screen flex items-center justify-center bg-gray-100">
            <div className="w-full max-w-md p-8 space-y-8 bg-white rounded-lg shadow-md flex flex-col items-center">
                {children}
            </div>
            </body>
            </html>
        </ClerkProvider>
    );
}